# Generated by Django 3.0.6 on 2020-06-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200620_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiftBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnroadBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='main_banner',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='page_heading',
        ),
        migrations.RemoveField(
            model_name='lifting',
            name='lift_banner',
        ),
        migrations.RemoveField(
            model_name='lifting',
            name='page_heading',
        ),
        migrations.RemoveField(
            model_name='onroad',
            name='page_heading',
        ),
        migrations.RenameModel(
            old_name='Photo',
            new_name='TransportBanner',
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_description', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.TransportBanner')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.EquipBanner'),
        ),
        migrations.AddField(
            model_name='lifting',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.LiftBanner'),
        ),
        migrations.AddField(
            model_name='onroad',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.OnroadBanner'),
        ),
    ]
