# Generated by Django 3.0.6 on 2020-06-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200621_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutbanner',
            options={'verbose_name': 'About Us Banner', 'verbose_name_plural': 'About - Banner'},
        ),
        migrations.AlterModelOptions(
            name='contactbanner',
            options={'verbose_name': 'Contact Banner', 'verbose_name_plural': 'Contact-Banner'},
        ),
        migrations.AlterModelOptions(
            name='enquirybanner',
            options={'verbose_name': 'Enquiry Banner', 'verbose_name_plural': 'Enquiry-Banner'},
        ),
        migrations.CreateModel(
            name='HomeBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('caption', models.CharField(blank=True, max_length=50, null=True)),
                ('title1', models.CharField(blank=True, max_length=50, null=True)),
                ('title2', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Slider')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.ServiceBanner'),
        ),
    ]
