# Generated by Django 3.0.6 on 2020-06-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='test',
            name='info',
        ),
        migrations.RemoveField(
            model_name='test',
            name='link',
        ),
        migrations.RemoveField(
            model_name='test',
            name='price',
        ),
        migrations.RemoveField(
            model_name='test',
            name='price_description',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
        migrations.AddField(
            model_name='test',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='title1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='title2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='HomeBody',
        ),
    ]
