# Generated by Django 3.0.6 on 2020-06-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200622_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homecontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, max_length=50, null=True)),
                ('contact', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Home Contact',
                'verbose_name_plural': 'Home Contact',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
