# Generated by Django 3.0.6 on 2020-06-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200622_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socialiconlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.URLField(blank=True, max_length=100, null=True)),
                ('insta', models.URLField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'ABOUT US ', 'verbose_name_plural': 'ABOUT US'},
        ),
        migrations.AlterModelOptions(
            name='aboutbanner',
            options={'verbose_name': 'ABOUT US BANNER', 'verbose_name_plural': 'ABOUT US BANNER'},
        ),
        migrations.AlterModelOptions(
            name='construction',
            options={'verbose_name': 'CONSTRUCTION EQUIPMENT', 'verbose_name_plural': 'CONSTRUCTION EQUIPMENT'},
        ),
        migrations.AlterModelOptions(
            name='constructionbanner',
            options={'verbose_name': 'CONSTRUCTION BANNER', 'verbose_name_plural': 'CONSTRUCTION BANNER'},
        ),
        migrations.AlterModelOptions(
            name='contactbanner',
            options={'verbose_name': 'CONTACT BANNER', 'verbose_name_plural': 'CONTACT BANNER'},
        ),
        migrations.AlterModelOptions(
            name='enquirybanner',
            options={'verbose_name': 'ENQUIRY BANNERY BANNER', 'verbose_name_plural': 'ENQUIRY BANNERY BANNER'},
        ),
        migrations.AlterModelOptions(
            name='equipbanner',
            options={'verbose_name': 'EQUIPMENT BANNER ', 'verbose_name_plural': 'EQUIPMENT BANNER'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'EQUIPMENTS', 'verbose_name_plural': 'EQUIPMENTS'},
        ),
        migrations.AlterModelOptions(
            name='homecontact',
            options={'verbose_name': 'HOME PAGE CONTACT', 'verbose_name_plural': 'HOME PAGE CONTACT'},
        ),
        migrations.AlterModelOptions(
            name='liftbanner',
            options={'verbose_name': 'LIFTING EQUIPMENT BANNER ', 'verbose_name_plural': 'LIFTING EQUIPMENT BANNER'},
        ),
        migrations.AlterModelOptions(
            name='lifting',
            options={'verbose_name': 'LIFTING EQUIPMENT', 'verbose_name_plural': 'LIFTING EQUIPMENT'},
        ),
        migrations.AlterModelOptions(
            name='logoequipment',
            options={'verbose_name': 'LOGO EQUIPMENT ', 'verbose_name_plural': 'LOGO EQUIPMENT'},
        ),
        migrations.AlterModelOptions(
            name='onroad',
            options={'verbose_name': 'ON ROAD EQUIPMENT', 'verbose_name_plural': 'ON ROAD EQUIPMENT'},
        ),
        migrations.AlterModelOptions(
            name='onroadbanner',
            options={'verbose_name': 'ON ROAD EQUIPMENT Banner', 'verbose_name_plural': 'ON ROAD EQUIPMENT Banner'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'SERVICES ', 'verbose_name_plural': 'SERVICES'},
        ),
        migrations.AlterModelOptions(
            name='servicebanner',
            options={'verbose_name': 'SERVICES BANNER ', 'verbose_name_plural': 'SERVICES BANNER'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'HOME SLIDER ', 'verbose_name_plural': 'HOME SLIDER'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'HOME BODY ', 'verbose_name_plural': 'HOME BODY'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'TRANSPORTATION', 'verbose_name_plural': 'TRANSPORTATION'},
        ),
        migrations.AlterModelOptions(
            name='transportbanner',
            options={'verbose_name': 'TRANSPORT BANNER', 'verbose_name_plural': 'TRANSPORT BANNER'},
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='geolocation',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logoequipment',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homecontact',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
